---
- hosts: test
  tasks:
 
    - name: Install package nginx
      apt: name=nginx update_cache=yes
      sudo: no
   
    - name: Starting service nginx
      service: name=nginx state=started
      sudo: no
