---
- hosts: test
  tasks:
 
    - name: Install package apache2
      apt: name=apache2 update_cache=yes
      sudo: no
   
    - name: Starting service appache2
      service: name=apache2 state=started
      sudo: no
